#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1

cd branch

docker buildx build . \
    -f Dockerfile \
    -t $IMAGE_NAME \
    --platform linux/amd64,linux/arm64 \
    --progress plain \
    --push
