#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1

docker buildx build . \
	--platform linux/amd64,linux/arm64 \
    --progress plain --load \
	-f $DOCKERFILE_PATH \
    -t $IMAGE_NAME